require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Runs a Pry console"
task :console do
  # This line turns on logging of the SQL generated by Active Record
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  
  # Open a Pry session
  Pry.start
end
namespace :db do
  desc 'migrate changes to your database'
  task migrate: :environment do
    # Costume.create_table
    # CostumeStore.create_table
    # HauntedHouse.create_table
  end
end
